import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Nav/Navbar";
import { Toaster } from "react-hot-toast";
// import { Provider } from "react-redux";
// import store from "@/redux/store";
import ReduxProvider from "@/components/ReduxProvider";
import Footer from "@/components/Footer/idex";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} dark:bg-[#030712]`}>
        <ReduxProvider>
          <Toaster position="top-center" reverseOrder={false} />
          <Navbar />
          {children}
          <Footer />
          {/* <Toaster /> */}
        </ReduxProvider>
      </body>
    </html>
  );
}
